#!/bin/sh

if (which dpkg | grep -q /dpkg)
then
	echo "System: Ubuntu/Debian"
	if (dpkg -s myiphide | grep -q "installed")
	then
		echo "Uninstallation start."
		sudo dpkg -r myiphide
	else
		echo "Installation start."
		wget -N http://myiphide.com/download/myiphide.deb
		sudo dpkg -i myiphide.deb
		myiphide &
	fi
elif (which rpm | grep -q /rpm)
then
	echo "System: Redhat/Fedora/CentOS"
	if (rpm -q myiphide | grep -q ".x86_64")
	then
		echo "Uninstallation start."
		sudo rpm -e myiphide
	else
		wget -N http://myiphide.com/download/myiphide.rpm
		sudo rpm -ihv myiphide.rpm
		myiphide &
	fi
else
	echo "Action failed."
	echo "Your system may not support deb or rpm files."
fi
